# ============================================================================
# WARNING: AUTO-GENERATED FILE - DO NOT MODIFY MANUALLY!
# ============================================================================
# This file is automatically generated by client_tools/client_generator.py
# Any manual changes will be overwritten when the generator runs again.
#
# To update this file:
#   1. Modify the source files in src/twinkle/
#   2. Run: python client_tools/client_generator.py
# ============================================================================

from typing import List, Literal, Optional, Union
from twinkle_client.http import http_post
from twinkle import DeviceMesh
from twinkle.data_format import InputFeature

class InputProcessor(object):
    """Client wrapper for InputProcessor that calls server HTTP endpoints."""

    def __init__(self, device_mesh: Optional[DeviceMesh] = None, padding_free: bool = False, framework: Literal['transformers', 'megatron'] = 'transformers', **kwargs):
        from twinkle_client.http import get_base_url

        self.server_url = f'{get_base_url()}/processor/twinkle'
        response = http_post(
            url=f'{self.server_url}/create',
            json_data={
                'processor_type': 'processor',
                'class_type': 'InputProcessor',
                **{'device_mesh': device_mesh, 'padding_free': padding_free, 'framework': framework}, **kwargs
            }
        )
        response.raise_for_status()
        self.processor_id = response.json()['processor_id']

    
    def __call__(self, inputs: Union[InputFeature, List[InputFeature]], **kwargs):
        response = http_post(
            url=f'{self.server_url}/call',
            json_data={
                'processor_id': self.processor_id,
                'function': '__call__',
                **{'inputs': inputs},
                **kwargs
            }
        )
        response.raise_for_status()
        return response.json()["result"]
    